cmake_minimum_required(VERSION 3.20 FATAL_ERROR)

project(tnt LANGUAGES C)

if(NOT TNT_CONF_DIR)
  set(TNT_CONF_DIR "/usr/local/share/tnt/conf")
endif()
if(NOT TNT_EDITOR)
  set(TNT_EDITOR "vi")
endif()
option(USE_NLS "use NLS" OFF)
option(GEN_NEW_USER "enable newuser generation" OFF)
option(TNT_SOUND "sound support" OFF)
option(USE_AX25K "use the Linux AX25 Kernel" OFF)
option(USE_AX25K2 "use the Linux AX25 Kernel 2.2.x and new axutils" OFF)
option(DPBOXT "compile for use with dpboxt" OFF)
option(USE_HIBAUD "use hibaud-rate (>38400), only on Linux" OFF)

find_package(Intl REQUIRED)
include_directories(${Intl_INCLUDE_DIRS} ${CMAKE_SOURCE_DIR})

include(CheckFunctionExists)
check_function_exists(index HAVE_INDEX)
check_function_exists(memmove HAVE_MEMMOVE)
check_function_exists(srandom HAVE_SRANDOM)
check_function_exists(usleep HAVE_USLEEP)

include(CheckIncludeFile)
check_include_file(libintl.h HAVE_LIBINTL_H)
check_include_file(locale.h HAVE_LOCALE_H)
check_include_file(termcap.h HAVE_TERMCAP_H)
check_include_file(termio.h HAVE_TERMIO_H)
check_include_file(wait.h HAVE_WAIT_H)
check_include_file(sys/select.h HAVE_SYS_SELECT_H)
check_include_file(sys/wait.h HAVE_SYS_WAIT_H)
check_include_file(netax25/ax25.h HAVE_NETAX25_AX25_H)
check_include_file(netax25/procutils.h HAVE_NETAX25_PROCUTILS_H)
check_include_file(netrom/netrom.h HAVE_NETROM_NETROM_H)
check_include_file(netrose/rose.h HAVE_NETROSE_ROSE_H)

set(CONFIG_H ${CMAKE_SOURCE_DIR}/config.h)
file(WRITE ${CONFIG_H} "/* this is auto-generated */\n")
if(("${CMAKE_SYSTEM_NAME}" STREQUAL "NetBSD") OR
   ("${CMAKE_SYSTEM_NAME}" STREQUAL "DragonFly") OR
   ("${CMAKE_SYSTEM_NAME}" STREQUAL "OpenBSD"))
  file(APPEND ${CONFIG_H} "#define TNT_NETBSD 1\n")
elseif(("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux"))
  file(APPEND ${CONFIG_H} "#define TNT_LINUX 1\n")
elseif(("${CMAKE_SYSTEM_NAME}" STREQUAL "SunOS"))
  file(APPEND ${CONFIG_H} "#define TNT_SOLARIS 1\n")
endif()

file(APPEND ${CONFIG_H} "#define DIR_STRING \"ls -la \"\n")
file(APPEND ${CONFIG_H} "#define DIRL_STRING \"ls -la \"\n")
file(APPEND ${CONFIG_H} "#define DIRRUN_STRING \"ls \"\n")
file(APPEND ${CONFIG_H} "#define FREE_STRING \"df 2>/dev/null > \"\n")
file(APPEND ${CONFIG_H} "#define BCAST 1\n")
file(APPEND ${CONFIG_H} "#define USE_IFACE 1\n")
file(APPEND ${CONFIG_H} "#define DEF_AUTO_NEWLINE 0\n")
file(APPEND ${CONFIG_H} "#define DEF_SUPP_HICNTL 0\n")
file(APPEND ${CONFIG_H} "#define DEF_TERMCAP 0\n")
file(APPEND ${CONFIG_H} "#define DEF_COLOR 1\n")
file(APPEND ${CONFIG_H} "#define HAVE_CRTSCTS 1\n")
file(APPEND ${CONFIG_H} "#define HAVE_SOCKET 1\n")
file(APPEND ${CONFIG_H} "#define HAVE_SOCKLEN_T 1\n")
file(APPEND ${CONFIG_H} "#define TNT_INIT_PATH \"${TNT_CONF_DIR}\"\n")
file(APPEND ${CONFIG_H} "#define DEFAULT_EDITOR \"${TNT_EDITOR}\"\n")

if(USE_NLS)
  file(APPEND ${CONFIG_H} "#define HAVE_NLS 1\n")
endif()
if(GEN_NEW_USER)
  file(APPEND ${CONFIG_H} "#define GEN_NEW_USER 1\n")
endif()
if(TNT_SOUND)
  file(APPEND ${CONFIG_H} "#define TNT_SOUND 1\n")
endif()
if(USE_AX25K)
  file(APPEND ${CONFIG_H} "#define USE_AX25K 1\n")
endif()
if(USE_AX25K2)
  file(APPEND ${CONFIG_H} "#define USE_AX25K 1\n")
  file(APPEND ${CONFIG_H} "#define USE_AX25K2 1\n")
endif()
if(DPBOXT)
  file(APPEND ${CONFIG_H} "#define DPBOXT 1\n")
endif()
if(USE_HIBAUD)
  file(APPEND ${CONFIG_H} "#define USE_HIBAUD 1\n")
endif()
if(HAVE_INDEX)
  file(APPEND ${CONFIG_H} "#define HAVE_INDEX 1\n")
endif()
if(HAVE_MEMMOVE)
  file(APPEND ${CONFIG_H} "#define HAVE_MEMMOVE 1\n")
endif()
if(HAVE_SRANDOM)
  file(APPEND ${CONFIG_H} "#define HAVE_SRANDOM 1\n")
endif()
if(HAVE_USLEEP)
  file(APPEND ${CONFIG_H} "#define HAVE_USLEEP 1\n")
endif()
if(HAVE_LIBINTL_H)
  file(APPEND ${CONFIG_H} "#define HAVE_LIBINTL_H 1\n")
endif()
if(HAVE_LOCALE_H)
  file(APPEND ${CONFIG_H} "#define HAVE_LOCALE_H 1\n")
endif()
if(HAVE_TERMCAP_H)
  file(APPEND ${CONFIG_H} "#define HAVE_TERMCAP_H 1\n")
endif()
if(HAVE_TERMIO_H)
  file(APPEND ${CONFIG_H} "#define HAVE_TERMIO_H 1\n")
endif()
if(HAVE_WAIT_H)
  file(APPEND ${CONFIG_H} "#define HAVE_WAIT_H 1\n")
endif()
if(HAVE_SYS_SELECT_H)
  file(APPEND ${CONFIG_H} "#define HAVE_SYS_SELECT_H 1\n")
endif()
if(HAVE_SYS_WAIT_H)
  file(APPEND ${CONFIG_H} "#define HAVE_SYS_WAIT_H 1\n")
endif()
if(HAVE_NETAX25_AX25_H)
  file(APPEND ${CONFIG_H} "#define HAVE_NETAX25_AX25_H 1\n")
endif()
if(HAVE_NETAX25_PROCUTILS_H)
  file(APPEND ${CONFIG_H} "#define HAVE_NETAX25_PROCUTILS_H 1\n")
endif()
if(HAVE_NETROM_NETROM_H)
  file(APPEND ${CONFIG_H} "#define HAVE_NETROM_NETROM_H 1\n")
endif()
if(HAVE_NETROSE_ROSE_H)
  file(APPEND ${CONFIG_H} "#define HAVE_NETROSE_ROSE_H 1\n")
endif()

add_subdirectory(src)
